"""empty message

Revision ID: ea173bbb818a
Revises: bded01bf3bd1
Create Date: 2024-02-05 18:59:23.200447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea173bbb818a'
down_revision = 'bded01bf3bd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retreat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('cost', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('retreat', schema=None) as batch_op:
        batch_op.drop_column('cost')
        batch_op.drop_column('date')
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
